name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username CangioUni --password ${{ secrets.GH_PAT }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/cangiouni/shelly-exporter:latest
        docker push ghcr.io/CangioUni/shelly-exporter:latest
